In [1]:
import numpy as np
import pandas as pd
from scipy import stats

Q.1

In [3]:
df = pd.read_csv("D:/Data Science- Assignments folder/New folder/Cutlets.csv")

In [4]:
df

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [6]:
UnitA = df.iloc[:,0]

In [7]:
UnitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [8]:
UnitB = df.iloc[:,1]
UnitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [9]:
stats.ttest_ind(UnitA, UnitB)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

Q.2

In [11]:
df1 = pd.read_csv("D:/Data Science- Assignments folder/New folder/LabTAT.csv")

In [12]:
df1

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [18]:
Lab1 = df1.iloc[:,0]
Lab1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...  
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [21]:
Lab2 = df1.iloc[:,1]
Lab2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [22]:
Lab3 = df1.iloc[:,2]
Lab3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...  
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [23]:
Lab4 = df1.iloc[:,3]
Lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [24]:
stats.f_oneway(Lab1, Lab2, Lab3, Lab4)

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

Q.3

In [26]:
df2 = pd.read_csv("D:/Data Science- Assignments folder/New folder/BuyerRatio.csv")

In [27]:
df2

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
#For checking  purpose we have calculated the Ratios mathematically below

In [42]:
r1E = df2.iloc[0,1] / df2.iloc[1,1]
r1E
print("Ratio of male-female for East region is: ", r1E)

Ratio of male-female for East region is:  0.11494252873563218


In [41]:
r2W = df2.iloc[0,2] / df2.iloc[1,2]
r2W
print("Ratio of male-female for West region is: ", r2W)

Ratio of male-female for West region is:  0.09323703217334209


In [40]:
r3N = df2.iloc[0,3] / df2.iloc[1,3]
r3N
print("Ratio of male-female for North region is: ", r3N)

Ratio of male-female for North region is:  0.09660766961651918


In [37]:
r4S = df2.iloc[0,4] / df2.iloc[1,4]
r4S
print("Ratio of male-female for South region is: ", r4S)

Ratio of male-female for South region is:  0.09333333333333334


In [46]:
East = df2.iloc[:,1]
East

0     50
1    435
Name: East, dtype: int64

In [48]:
West = df2.iloc[:,2]
West

0     142
1    1523
Name: West, dtype: int64

In [50]:
North = df2.iloc[:,3]
North

0     131
1    1356
Name: North, dtype: int64

In [51]:
South = df2.iloc[:,4]
South

0     70
1    750
Name: South, dtype: int64

In [52]:
stats.f_oneway(East, West, North, South)

F_onewayResult(statistic=0.3068565327605033, pvalue=0.8204060154887464)

Q.4

In [3]:
data_cust = pd.read_csv("D:/Data Science- Assignments folder/New folder/Costomer+OrderForm.csv")
data_cust

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [7]:
dum = pd.get_dummies(data_cust)
dum

Phillippines_Defective  Phillippines_Error Free  Indonesia_Defective  \
0                         0                        1                    0   
1                         0                        1                    0   
2                         0                        1                    1   
3                         0                        1                    0   
4                         0                        1                    0   
..                      ...                      ...                  ...   
295                       0                        1                    0   
296                       0                        1                    0   
297                       0                        1                    0   
298                       0                        1                    0   
299                       0                        1                    1   

     Indonesia_Error Free  Malta_Defective  Malta_Error Free  India_Defective  \
0                       1                1                 0                0   
1                       1                0                 1                1   
2                       0                1                 0                0   
3                       1                0                 1                0   
4                       1                1                 0                0   
..                    ...              ...               ...              ...   
295                     1                0                 1                0   
296                     1                0                 1                0   
297                     1                1                 0                0   
298                     1                0                 1                0   
299                     0                1                 0                0   

     India_Error Free  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
295                 1  
296                 1  
297                 1  
298                 1  
299                 1  

[300 rows x 8 columns]

In [17]:
defective = dum.iloc[:,[0,2,4,6]]
defective

Phillippines_Defective  Indonesia_Defective  Malta_Defective  \
0                         0                    0                1   
1                         0                    0                0   
2                         0                    1                1   
3                         0                    0                0   
4                         0                    0                1   
..                      ...                  ...              ...   
295                       0                    0                0   
296                       0                    0                0   
297                       0                    0                1   
298                       0                    0                0   
299                       0                    1                1   

     India_Defective  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0  
..               ...  
295                0  
296                0  
297                0  
298                0  
299                0  

[300 rows x 4 columns]

In [21]:
Pdef = defective.iloc[:,0]
Pdef

0      0
1      0
2      0
3      0
4      0
      ..
295    0
296    0
297    0
298    0
299    0
Name: Phillippines_Defective, Length: 300, dtype: uint8

In [22]:
Idef = defective.iloc[:,1]
Idef

0      0
1      0
2      1
3      0
4      0
      ..
295    0
296    0
297    0
298    0
299    1
Name: Indonesia_Defective, Length: 300, dtype: uint8

In [23]:
Mdef = defective.iloc[:,2]
Mdef

0      1
1      0
2      1
3      0
4      1
      ..
295    0
296    0
297    1
298    0
299    1
Name: Malta_Defective, Length: 300, dtype: uint8

In [24]:
IndDef = defective.iloc[:,3]
IndDef

0      0
1      1
2      0
3      0
4      0
      ..
295    0
296    0
297    0
298    0
299    0
Name: India_Defective, Length: 300, dtype: uint8

In [25]:
stats.f_oneway(Pdef, Idef, Mdef, IndDef)

F_onewayResult(statistic=1.286168556089167, pvalue=0.2776780955705948)

In [8]:
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(dum)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 1200.0.
p value is 1.0.
df is 2093.
Expected table is 
[[0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 ...
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]
 [0.09666667 0.90333333 0.11       ... 0.89666667 0.06666667 0.93333333]]


In [9]:
cd


C:\Users\Sushant Vahalkar
